### ISSUE TITLE
One 'th' tag missing in datagridwidget.pt edit macro

### ISSUE THREAD

**Issue by gbastien** [collective/Products.DataGridField#1]
This is ticket #37 from the Plone TRAC.

In the skins/.../datagridwidget.pt, the macro responsible for the edit part is missing one empty <th />. In fact, there are 3 </th> where 4 could be necessary in case we can move rows (2 th), add a row and remove a row. If you want to style the THEAD, this can be a problem. We at least need to add a <th /> but even, these <th /> sould appear depending on the options activated on the field : allow_insert, allow_delete, allow_reorder. I will branch and propose a "Pull request"

**Comment by gbastien** [comment]
PR was merged a long time ago...

**Comment by mauritsvanrees** [comment]
Good. Thanks for checking and cleaning up the tracker!
