### ISSUE TITLE
Column.visible should work the same way AT Widget does

### ISSUE THREAD

**Issue by gbastien** [collective/Products.DataGridField#25]
Hi @mauritsvanrees 

I would like to extend the way the property "visible" works and make it works like in AT :

- either use values True/False;
- or use a dict like { 'edit' :'hidden', 'view': 'invisible' }.

For now if it is set to visible=False, it correspond to { 'edit' :'hidden', 'view': 'invisible' }.

What do you think, is it OK to propose a PR regarding this?

Thank you!

Gauthier

**Comment by mauritsvanrees** [comment]
Sounds okay to me.
Of course migration would be needed.

**Comment by gbastien** [comment]
Hi @mauritsvanrees 

I would keep the current way (True/False) and add the dict-like way, so I think (???) migration should not be needed, except documentation update.

I will propose something soon.

Thank you,

Gauthier

**Comment by mauritsvanrees** [comment]
Ah, right. Sounds good.

**Comment by gbastien** [comment]
@mauritsvanrees 

looking at the code and moving our stuffs to Dexterity, I think it will be to much work, especially because there are not enough tests for now...

I will propose something lighter, it is naming the th/td using the 'dgw-hidden-column' class with the column id so it can be done (show or hide) in view/edit mode using CSS...

Gauthier

**Comment by mauritsvanrees** [comment]
For dexterity, I would expect collective.z3cform.datagridfield is working well, so indeed no need to move to dexterity.

**Comment by gbastien** [comment]
@mauritsvanrees 

looking at the code, it was the idea I think, an hidden column is using class "dgw-hidden-column %s" for now, the %s was supposed to be used ;-)

I would generate a class like "dgw-hidden-column column_id" for displayed <th> and <td> in the "view" mode, indeed in "edit" mode, there is already what necessary to show/hide it using CSS, the generated class is like : "dgw-hidden-column datagridwidget-column-1 discreet".

I would generate a class in "view" mode that is exactly the same as in "edit" mode (minus the "discreet" maybe), but I am a bit afraid of side effects for existing tables...

What do you think?

Either something like "dgw-hidden-column datagridwidget-column-1" or "dgw-hidden-column column_id".

Gauthier

**Comment by mauritsvanrees** [comment]
I have merged your pull request #26 which does part of the above. Do you still want to work on supporting the dict-like way?

**Comment by gbastien** [comment]
I will not, we have enough with #26 

Thank you for review and merge!

Gauthier

**Comment by mauritsvanrees** [comment]
I have released 1.9.5 with this.

**Comment by gbastien** [comment]
Great!

Thank you,

Gauthier
